heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: cirros-0.3.4-x86_64
      flavor: m1.small
      key_name: bougou

  my_volume:
    type: OS::Cinder::Volume
    properties:
      size: 10

  my_attach:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: my_instance }
      volume_id: { get_resource: my_volume }
      
