#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <file>"
  echo "<file> will be used as the temporary haproxy.cfg file generated by this script."
  exit 1
fi

SCRIPT_DIR=$(dirname $0)
BASE_DIR=$(cd $SCRIPT_DIR/..; pwd)
source $BASE_DIR/load-environment.sh

## Generate haproxy.cfg from template.
# HAPROXY_CFG=/tmp/haproxy.cfg.tmp
HAPROXY_CFG=$1
> $HAPROXY_CFG

for ha in `ls $CONF_BASE/haproxy/general.*.ha`; do
  cat $ha >> $HAPROXY_CFG
  echo >> $HAPROXY_CFG
done

for ha in `ls $CONF_BASE/haproxy/listen.*.ha`; do
  cat $ha >> $HAPROXY_CFG
  # listen.5672.rabbitmq.ha
  port=$(basename $ha | awk -F. '{print $2}')
   
  [[ $port != "35357" ]] &&
    echo "  bind $CONT_API_IP:$port" >>$HAPROXY_CFG

  [[ $port != "5000" ]] &&
    echo "  bind $CONT_MGMT_IP:$port" >>$HAPROXY_CFG

  while read n_ip n_hostname n_ext_ip; do
    [[ $port == "5000" ]] && server_ip=$n_ext_ip || server_ip=$n_ip
    echo "  server $n_hostname $server_ip:$port check inter 2000 rise 2 fall 5" >> $HAPROXY_CFG
  done < $MAP_BASE/controller-node.list

  echo >>  $HAPROXY_CFG
done
